### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by NotSwaraj** [Bennitenni111/Nitro-Generator#2]
bro imagine skidding lmfao, you dont even know there is a thing called ratelimits, you copied someone's popular gen and put your motherfucking name on it, get a life skidding cunt. also your nitro sniper doesnt even auto claim LOL wtf skid 100

**Comment by NotSwaraj** [comment]
I mean on ur other gen + checker shit

**Comment by NotSwaraj** [comment]
oh look it got closed lol

**Comment by pjmangaming** [comment]
lol
